services:
  mongo:
    image: mongo:7
    container_name: university-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
      - ./instructors.json:/seed/instructors.json
      - ./courses.json:/seed/courses.json
      - ./load-data.sh:/docker-entrypoint-initdb.d/load-data.sh
