version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: university-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
      - ./init/load-data.sh:/docker-entrypoint-initdb.d/load-data.sh
